---
title: "Predicting District School Funding and Educational Outcomes"
author: "Team Po-Data Science: Amy Luo, Austin Tucker, Han Choi, Juliet McCann, Yeeun Lee"
date: "December 2021"
output:
  html_document:
    theme:
      bootswatch: 'cosmo'
    df_print: paged
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 

## Overview and Motivation
*Provide an overview of the project goals and the motivation for it. Consider that this will be read by people who did not see your project proposal.*



## Related Work
*Anything that inspired you, such as a paper, a web site, or something we discussed in class.*

## Initial Questions
*What questions are you trying to answer? How did these questions evolve over the course of the project? What new questions did you consider in the course of your analysis?*


## Part 1: Predicting District Academic Achievement

### Data Source:

### Explorotory Analysis

### Part 1a: Deciding the predictors of interest



Initial Questions: What questions are you trying to answer? How did these questions evolve over the course of the project? What new questions did you consider in the course of your analysis?








